### ISSUE TITLE
Add Foreign Name Scraping

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/GathererScraper#10]
Card names are available in [different languages](http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=193556). GathererScraper should download this information and build it into the patches.
The available languages are:

- Chinese Simplified
- Chinese Traditional
- French
- German
- Italian
- Japanese
- Korean
- Portuguese (Brazil)
- Russian
- Spanish

**Comment by AEFeinstein** [comment]
This ticket is related to https://github.com/AEFeinstein/mtg-familiar/issues/182

**Comment by AEFeinstein** [comment]
@Haerezis I would like to start the translation, beta, and release process for Familiar in two weeks (April 4th). Can this feature be implemented by then?
edit: this feature too, https://github.com/AEFeinstein/mtg-familiar/issues/182

**Comment by Haerezis** [comment]
Sorry, I was busy during the beginning of the week.
The scrapper should be ok, so the Card class will also be ok, but I don't know about the rest of AEFeinstein/mtg-familiar#182. I've never worked on the card db of mtg-familiar, so I might take some time to figure things out.

**Comment by AEFeinstein** [comment]
AEFeinstein/mtg-familiar#182 should be pretty easy for me to do, so I can handle that if you finish this ticket.

**Comment by Haerezis** [comment]
Ok. I'll work on it this weekend.

**Comment by Haerezis** [comment]
Tell me if the PR is ok or if you want me to change something.

**Comment by AEFeinstein** [comment]
PR looks good. The only odd thing I noticed during spot-checking was that different printings of the same card don't always have the same language data. It appears to be dependent on that printing's variations:
http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=386287
http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=180516
I guess the app will have to look at all versions of a card for the dialog...

**Comment by AEFeinstein** [comment]
There is an encoding problem with the patches. Even though it scrapes correctly and displays the right name in the Java debugger, when it's written to a file, non-English characters are saved as ?, like this:

```
"name": "Scion of Ugin",
"foreignNames": {
  "de": "Ugins Spross",
  "ru": "??????? ??????",
  "zh_HANS": "????",
  "ko": "??? ??",
  "ja": "??????",
  "it": "Erede di Ugin",
  "pt_BR": "Herdeiro de Ugin",
  "zh_HANT": "????",
  "fr": "Scion d'Ugin",
  "es": "Vástago de Ugin"
},
```

I think you have to explicitly use UTF-8 here (maybe UTF-16).

**Comment by AEFeinstein** [comment]
Fixed in 151c7f8cbe5303d77bdcb527de34802129579bb6

**Comment by Haerezis** [comment]
Sorry, I never saw the email with your message notification :/ that's why I didn't fixed the issue.

**Comment by AEFeinstein** [comment]
No worries.
